version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: notes
    ports:
      - "5432:5432"

  flask-app:
    build:
      context: .
    image: luizfsborges/ponderada2
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://teste:teste123@postgres:5432/notes
