version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      - DB_HOST=localhost  # Use localhost since it's on the same Docker host
      - DB_PORT=5432      # Specify the port for PostgreSQL
      - DB_USER=teste
      - DB_PASSWORD=teste123
      - DB_NAME=notes
    ports:
      - "5432:5432"

  flask-app:
    build:
      context: .
    image: luizfsborges/ponderada2
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://teste:teste123@postgres:5432/notes
